import type { RawCsvEvent } from "./types";

// Representative sample month so users can explore the workstation without
// needing to provide their own CSV. Mirrors the shape of the Airtable export.
export const SAMPLE_RAW_EVENTS: RawCsvEvent[] = [
  {
    Title: "Opening Reception: Light & Form",
    Venue: "Five Points Gallery",
    Town: "Torrington",
    Website: "https://fivepointsarts.org",
    "Start At": "2026-01-03T18:00:00",
    "End At": "2026-01-03T20:00:00",
    Times: "",
    "Run Type": "Short Run",
    "Image URL": "",
  },
  {
    Title: "Community Figure Drawing",
    Venue: "NWCT Arts Council",
    Town: "Torrington",
    Website: "https://artsnwct.org",
    "Start At": "2026-01-07T18:30:00",
    "End At": "2026-01-07T20:30:00",
    Times: "",
    "Run Type": "Short Run",
    "Image URL": "",
  },
  {
    Title: "Winter Makers Market",
    Venue: "Whiting Mills",
    Town: "Winsted",
    Website: "https://whitingmills.com",
    "Start At": "2026-01-10T10:00:00",
    "End At": "2026-01-10T15:00:00",
    Times: "",
    "Run Type": "Short Run",
    "Image URL": "",
  },
  {
    Title: "The Art of Seeing: Landscape Studies",
    Venue: "Kent Art Association",
    Town: "Kent",
    Website: "https://kentart.org",
    "Start At": "2026-01-03T12:00:00",
    "End At": "2026-01-25T17:00:00",
    Times: "Thu-Sun 12-5 pm",
    "Run Type": "Long Run",
    "Image URL": "",
  },
  {
    Title: "Reflections on Water",
    Venue: "Gallery 25",
    Town: "New Milford",
    Website: "https://gallery25ct.com",
    "Start At": "2026-01-05T11:00:00",
    "End At": "2026-01-31T16:00:00",
    Times: "Mon-Sat 11-4 pm",
    "Run Type": "Long Run",
    "Image URL": "",
  },
  {
    Title: "Clay Workshop Series",
    Venue: "The Village Center for the Arts",
    Town: "New Milford",
    Website: "https://villagecenterarts.org",
    "Start At": "2026-01-08T17:30:00",
    "End At": "2026-01-08T19:30:00",
    Times: "Thursdays 5:30-7:30 pm",
    "Run Type": "Workshop",
    "Image URL": "",
  },
  {
    Title: "Clay Workshop Series",
    Venue: "The Village Center for the Arts",
    Town: "New Milford",
    Website: "https://villagecenterarts.org",
    "Start At": "2026-01-15T17:30:00",
    "End At": "2026-01-15T19:30:00",
    Times: "Thursdays 5:30-7:30 pm",
    "Run Type": "Workshop",
    "Image URL": "",
  },
  {
    Title: "Clay Workshop Series",
    Venue: "The Village Center for the Arts",
    Town: "New Milford",
    Website: "https://villagecenterarts.org",
    "Start At": "2026-01-22T17:30:00",
    "End At": "2026-01-22T19:30:00",
    Times: "Thursdays 5:30-7:30 pm",
    "Run Type": "Workshop",
    "Image URL": "",
  },
  {
    Title: "Intro to Printmaking",
    Venue: "Five Points Arts Center",
    Town: "Torrington",
    Website: "https://fivepointsarts.org",
    "Start At": "2026-01-14T10:00:00",
    "End At": "2026-01-14T13:00:00",
    Times: "Wednesdays 10-1 pm",
    "Run Type": "Workshop",
    "Image URL": "",
  },
  {
    Title: "Intro to Printmaking",
    Venue: "Five Points Arts Center",
    Town: "Torrington",
    Website: "https://fivepointsarts.org",
    "Start At": "2026-01-21T10:00:00",
    "End At": "2026-01-21T13:00:00",
    Times: "Wednesdays 10-1 pm",
    "Run Type": "Workshop",
    "Image URL": "",
  },
];
