#!/usr/bin/env tsx
/**
 * Bug Fix Dashboard Generator
 */

import { getUnresolvedIssues } from '../lib/airtable';
import { categorizeBug } from './bug-taxonomy';
import { loadState } from './state-manager';
import fs from 'fs/promises';

interface DashboardData {
  total: number;
  fixed: number;
  remaining: number;
  byCategory: Record<string, number>;
  byPriority: Record<string, number>;
  recentActivity: DeploymentLog[];
}

interface DeploymentLog {
  timestamp: string;
  bugId: string;
  priority: string;
  deploySuccess: boolean;
  changes?: string[];
}

async function loadRecentActivity(): Promise<DeploymentLog[]> {
  try {
    const logPath = '/home/ethan/.openclaw/workspace/automation-lab/reports/bug-fixes/deployments.jsonl';
    const content = await fs.readFile(logPath, 'utf8');
    const lines = content.trim().split('\n').filter(Boolean);
    
    return lines.slice(-10).map(line => JSON.parse(line));
  } catch {
    return [];
  }
}

async function generateDashboard(): Promise<void> {
  const issues = await getUnresolvedIssues();
  const state = await loadState();
  const recentActivity = await loadRecentActivity();
  
  const byCategory: Record<string, number> = {};
  const byPriority: Record<string, number> = {};
  
  issues.forEach(issue => {
    const category = categorizeBug(issue.id);
    byCategory[category] = (byCategory[category] || 0) + 1;
    
    byPriority[issue.priority] = (byPriority[issue.priority] || 0) + 1;
  });
  
  const fixed = issues.filter(i => i.royFix).length;
  const remaining = issues.length - fixed;
  
  const data: DashboardData = {
    total: issues.length,
    fixed,
    remaining,
    byCategory,
    byPriority,
    recentActivity,
  };
  
  const markdown = `# 🐛 Bug Fix Dashboard

**Last Updated:** ${new Date().toLocaleString('en-US', { timeZone: 'America/New_York' })} ET

## 📊 Summary

- **Total Issues:** ${data.total}
- **✅ Fixed:** ${data.fixed} (${Math.round(fixed / data.total * 100)}%)
- **📝 Remaining:** ${data.remaining}

${state.currentBug ? `\n**🔧 Currently Working On:** ${state.currentBug}\n` : ''}

## 📂 By Category

${Object.entries(data.byCategory).map(([cat, count]) => 
  `- **${cat}:** ${count}`
).join('\n')}

## 🎯 By Priority

${Object.entries(data.byPriority).map(([pri, count]) => 
  `- **${pri}:** ${count}`
).join('\n')}

## 🔄 Recent Activity

${data.recentActivity.length === 0 ? '*No deployments yet*' : data.recentActivity.slice(-5).reverse().map(log => `
### ${log.deploySuccess ? '✅' : '❌'} ${log.bugId} (${log.priority})
- **Time:** ${new Date(log.timestamp).toLocaleString('en-US', { timeZone: 'America/New_York' })} ET
- **Status:** ${log.deploySuccess ? 'Deployed' : 'Failed'}
${log.changes ? `- **Changes:** ${log.changes.length} modification(s)` : ''}
`).join('\n')}

---
*Generated by automated bug-fix system*
`;

  await fs.writeFile(
    '/home/ethan/.openclaw/workspace/automation-lab/reports/bug-fixes/DASHBOARD.md',
    markdown
  );
  
  console.log('📊 Dashboard updated');
}

// Run if executed directly
if (require.main === module) {
  generateDashboard().catch(console.error);
}

export { generateDashboard };
